[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kascade"
version = "0.1.0"
description = "Sequential multi-photon inverse-Compton Monte Carlo engine (KASCADE)"
dependencies = [
    "numpy",
    "pint>=0.24"
]
requires-python = ">=3.10"

[tool.setuptools]
py-modules = ["kascade", "kascade_adapter"]
